{% set name = "xanadu-cloud-client" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xanadu-cloud-client-{{ version }}.tar.gz
  sha256: 563750ed72d2e9bbe428073bcb4ee02d751872d026207e90e88e928fab495ffb

build:
  number: 1
  noarch: python
  entry_points:
    - xcc=xcc.commands:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pydantic-settings
    - appdirs
    - fire
    - numpy
    - pydantic >=2
    - python >={{ python_min }}
    # From pydantic
    - python-dateutil
    - requests
    # Needed but not listed
    - python-dotenv

test:
  imports:
    - xcc
  commands:
    - pip check
    - xcc --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/XanaduAI/xanadu-cloud-client
  summary: XCC is a Python API and CLI for the Xanadu Cloud.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://xanadu-cloud-client.readthedocs.io/

extra:
  recipe-maintainers:
    - BastianZim
