{% set name = "xanadu-cloud-client" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xanadu-cloud-client-{{ version }}.tar.gz
  sha256: 5cbe6992d267683a066b1456d7afd14f2ee7df6163e249acbc95c202c9235129

build:
  number: 0
  noarch: python
  entry_points:
    - xcc=xcc.commands:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs
    - fire
    - numpy
    - pydantic
    - python >=3.6
    - python-dotenv >=0.10.4
    # From pydantic
    - python-dateutil
    - requests

test:
  imports:
    - xcc
  commands:
    - pip check
    - xcc --help
  requires:
    - pip

about:
  home: https://github.com/XanaduAI/xanadu-cloud-client
  summary: XCC is a Python API and CLI for the Xanadu Cloud.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://xanadu-cloud-client.readthedocs.io/

extra:
  recipe-maintainers:
    - BastianZim
